name       : libxfont2
version    : 2.0.5
release    : 10
source     :
    - https://www.x.org/releases/individual/lib/libXfont2-2.0.5.tar.gz : d7544aa35ea67a87840ff0b1bd15130b102e473de3611b7d78604ba635fd6d94
license    : MIT
component  : xorg.library
summary    : libXfont provides the core of the legacy X11 font system, handling the
    index files (fonts.dir, fonts.alias, fonts.scale), the various font file formats,
    and rasterizing them.
description: |
    libXfont provides the core of the legacy X11 font system, handling the index files (fonts.dir, fonts.alias, fonts.scale), the various font file formats, and rasterizing them.
optimize   :
    - speed
    - no-symbolic
emul32     : yes
builddeps  :
    - pkgconfig32(freetype2)
    - pkgconfig32(fontenc)
    - pkgconfig32(zlib)
    - pkgconfig(xproto)
    - pkgconfig(xtrans)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
