name       : libxfont2
version    : 2.0.1
release    : 1
source     :
    - https://www.x.org/releases/individual/lib/libXfont2-2.0.1.tar.gz : 381b6b385a69343df48a082523c856aed9042fbbc8ee0a6342fb502e4321230a
license    : MIT
component  : xorg.library
summary    : X11 font2 specification
description: |
    X11 font2 specification
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig32(freetype2)
    - pkgconfig32(zlib)
    - pkgconfig(xproto)
    - pkgconfig(fontenc)
    - pkgconfig32(fontenc)
    - pkgconfig(fontsproto)
    - pkgconfig(xtrans)
optimize   : speed
emul32     : yes
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
