name       : libxfont2
version    : 2.0.4
release    : 8
source     :
    - https://www.x.org/releases/individual/lib/libXfont2-2.0.4.tar.gz : 74e577294c7406b284c50dfcfb5e5d9b3b0cc2d83d33866920ffe1e4860f585a
license    : MIT
component  : xorg.library
summary    : X11 font2 specification
description: |
    X11 font2 specification
optimize   :
    - speed
    - no-symbolic
emul32     : yes
builddeps  :
    - pkgconfig(xproto)
    - pkgconfig32(freetype2)
    - pkgconfig32(fontenc)
    - pkgconfig32(zlib)
    - pkgconfig(xtrans)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
