name       : libxfont2
version    : 2.0.3
release    : 2
source     :
    - https://www.x.org/releases/individual/lib/libXfont2-2.0.3.tar.gz : a4b761a37528353a2b83dba364d7c1fd6aef2d554a1a019815f24f7f8866890e
license    : MIT
component  : xorg.library
summary    : X11 font2 specification
description: |
    X11 font2 specification
builddeps  :
    - pkgconfig(fontsproto)
    - pkgconfig(xproto)
    - pkgconfig32(freetype2)
    - pkgconfig32(fontenc)
    - pkgconfig32(zlib)
    - pkgconfig(xtrans)
optimize   :
    - speed
    - no-symbolic
emul32     : yes
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
